spring:
  application:
    name: discodeit
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5433/discodeit}
    username: ${DB_USERNAME:discodeit_user}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8081


logging:
  level:
    com.sprint.mission.discodeit: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: trace

management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
