spring:
  application:
    name: discodeit
#Repository 구현체 중에 어떤 구현체를 Bean으로 등록할지 Java 코드의 변경 없이 application.yaml 설정 값을 통해 제어
discodeit:
  repository:
    type: jcf             # jcf | file
    file-directory: .discodeit